modules/security/security-management/src/main/java/org/openiot/security/mgmt/HomeController.java
/**
 * Copyright (c) 2011-2014, OpenIoT
 *
 * This library is free software; you can redistribute it and/or
 * modify it either under the terms of the GNU Lesser General Public
 * License version 2.1 as published by the Free Software Foundation
 * (the "LGPL"). If you do not alter this
 * notice, a recipient may use your version of this file under the LGPL.
 *
 * You should have received a copy of the LGPL along with this library
 * in the file COPYING-LGPL-2.1; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY
 * OF ANY KIND, either express or implied. See the LGPL  for
 * the specific language governing rights and limitations.
 *
 * Contact: OpenIoT mailto: info@openiot.eu
 */

package org.openiot.security.mgmt;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

/**
 * @author Mehdi Riahi
 * 
 */
@ManagedBean
@ViewScoped
public class HomeController extends AbstractController {
	
}

modules/security/security-management/src/main/java/org/openiot/security/mgmt/PermissionsController.java
/**
 * Copyright (c) 2011-2014, OpenIoT
 *
 * This library is free software; you can redistribute it and/or
 * modify it either under the terms of the GNU Lesser General Public
 * License version 2.1 as published by the Free Software Foundation
 * (the "LGPL"). If you do not alter this
 * notice, a recipient may use your version of this file under the LGPL.
 *
 * You should have received a copy of the LGPL along with this library
 * in the file COPYING-LGPL-2.1; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY
 * OF ANY KIND, either express or implied. See the LGPL  for
 * the specific language governing rights and limitations.
 *
 * Contact: OpenIoT mailto: info@openiot.eu
 */

package org.openiot.security.mgmt;

import static org.openiot.security.mgmt.Utils.EmptyPermissionList;
import static org.openiot.security.mgmt.Utils.EmptyRoleList;
import static org.openiot.security.mgmt.Utils.EmptyUserList;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import org.jasig.cas.services.RegisteredService;
import org.openiot.lsm.security.oauth.mgmt.Permission;
import org.openiot.lsm.security.oauth.mgmt.Role;
import org.openiot.lsm.security.oauth.mgmt.User;
import org.primefaces.context.RequestContext;

/**
 * @author Mehdi Riahi
 * 
 */
@ManagedBean
@ViewScoped
public class PermissionsController extends AbstractController {

	private static final long serialVersionUID = -3531791896078368761L;

	private Permission selectedPermission;

	private Permission newPermission;

	private List<User> allUsers;

	private List<Role> allRoles;

	private List<Permission> allPermissions;

	private Map<Long, RegisteredService> allServices;

	private Map<Permission, List<Role>> permissionRoles;

	private Long selectedServiceId = -1L;

	private String selectedServiceIdStr = null;

	@ManagedProperty(value = "#{securityManagerService}")
	private SecurityManagerService securityManagerService;

	public PermissionsController() {

	}

	public List<Permission> getPermissions() {
		if (allPermissions == null) {
			allRoles = securityManagerService.getAllRoles();

			allUsers = securityManagerService.getAllUsers();
			allPermissions = securityManagerService.getAllPermissions();

			final List<RegisteredService> services = securityManagerService.getAllServices();
			allServices = new HashMap<Long, RegisteredService>(services.size());
			for (RegisteredService registeredService : services) {
				String name = registeredService.getName();
				if (Utils.acUtil.hasPermission("admin:user_mgmt:" + name))
					allServices.put(registeredService.getId(), registeredService);
			}
			permissionRoles = new HashMap<Permission, List<Role>>();
			for (Permission permission : allPermissions) {
				permissionRoles.put(permission, new ArrayList<Role>());
			}
			for (Role role : allRoles) {
				for (Permission permission : role.getPermissions()) {
					permissionRoles.get(permission).add(role);
				}
			}
		}
		if (selectedServiceId > -1) {
			// TODO: cache!
			List<Permission> list = new ArrayList<Permission>();
			for (Permission permission : allPermissions)
				if (permission.getServiceId().equals(selectedServiceId))
					list.add(permission);
			Collections.<Permission> sort(list, new PermissionComparator());
			return list;
		}
		return EmptyPermissionList;
	}

	public void setSecurityManagerService(SecurityManagerService securityManagerService) {
		this.securityManagerService = securityManagerService;
	}

	public void removePermission(Permission permission) {

		if (permission.equals(selectedPermission)) {
			List<Role> selectedPermissionRoles = getSelectedPermissionRoles();

			for (Role role : selectedPermissionRoles)
				role.getPermissions().remove(permission);

			securityManagerService.deletePermission(permission.getServiceId(), permission.getName());
			allPermissions.remove(selectedPermission);
			permissionRoles.remove(permission);
			addInfoMessage("Permission deleted", permission.getName());
			setSelectedPermission(null);
		}
	}

	public List<User> getSelectedPermissionUsers() {
		Set<User> permUsers = new HashSet<User>();
		if (selectedPermission != null) {
			for (User user : allUsers) {
				if (user.getRoles() == null)
					user.setRoles(new ArrayList<Role>());
				for (Role role : user.getRoles()) {
					if (role.getPermissions().contains(selectedPermission))
						permUsers.add(user);
				}
			}
			return new ArrayList<User>(permUsers);
		}
		return EmptyUserList;
	}

	public List<Role> getSelectedPermissionRoles() {
		List<Role> list = EmptyRoleList;
		if (selectedPermission != null)
			list = permissionRoles.get(selectedPermission);
		return list;
	}

	public Permission getSelectedPermission() {
		return selectedPermission;
	}

	public void setSelectedPermission(Permission selectedPermission) {
		this.selectedPermission = selectedPermission;
	}

	public List<RegisteredService> getAllServicesAsList() {
		if (allPermissions == null)
			getPermissions();
		return new ArrayList<RegisteredService>(allServices.values());
	}

	public RegisteredService getServiceById(Long serviceId) {
		return allServices.get(serviceId);
	}

	public Long getSelectedServiceId() {
		return selectedServiceId;
	}

	public void setSelectedServiceId(Long selectedServiceId) {
		this.selectedServiceId = selectedServiceId;
	}

	public String getSelectedServiceIdStr() {
		return selectedServiceIdStr;
	}

	public void setSelectedServiceIdStr(String selectedServiceIdStr) {
		this.selectedServiceIdStr = selectedServiceIdStr;
		try {
			setSelectedServiceId(Long.parseLong(selectedServiceIdStr));
		} catch (NumberFormatException e) {
			setSelectedServiceId(-1L);
		}
	}

	public String getSelectedServiceName() {
		if (allServices != null && selectedServiceId > -1 && allServices.containsKey(selectedServiceId))
			return allServices.get(selectedServiceId).getName();
		return "SELECTED_SERVICE_NOT_FOUND";
	}

	public boolean hasPermissionDeletionPermission() {
		return Utils.acUtil.hasPermission("admin:delete_permission:" + getSelectedServiceName());
	}

	public Permission getNewPermission() {
		if (newPermission == null)
			newPermission = new Permission();
		return newPermission;
	}

	public void cancelAddPermission() {
		newPermission = null;
	}

	public void addPermission() {
		boolean permissionAdded = false;
		if (selectedServiceId > -1 && newPermission != null && newPermission.getName().trim().length() > 0) {
			newPermission.setServiceId(selectedServiceId);
			if (isPermissionNameUnique(newPermission) & isPermissionNameValid(newPermission)) {
				securityManagerService.addPermission(newPermission);

				// updating permissions
				allPermissions.add(newPermission);
				permissionRoles.put(newPermission, new ArrayList<Role>());

				addInfoMessage("New permission added", newPermission.getName());
				newPermission = null;
				permissionAdded = true;
			} else {
				addErrorMessage("Adding new permission failed", "Permission name is not unique or permission name is not valid");
			}
		} else {
			addWarnMessage("There is no new permission to add", "");
		}
		RequestContext.getCurrentInstance().addCallbackParam("permissionAdded", permissionAdded);
	}

	public boolean isPermissionNameUnique(Permission permission) {
		for (Permission perm : allPermissions)
			if (permission.getServiceId().equals(perm.getServiceId()) && perm.getName().equals(permission.getName()))
				return false;
		return true;
	}

	public boolean isPermissionNameValid(Permission permission) {
		return !permission.getName().matches(".*(\\s|__|/).*");
	}

	private final class PermissionComparator implements Comparator<Permission> {
		@Override
		public int compare(Permission p1, Permission p2) {
			String end1;
			String end2;
			if (p1.getName().contains(":"))
				end1 = p1.getName().substring(p1.getName().lastIndexOf(":"));
			else
				end1 = p1.getName();
			if (p2.getName().contains(":"))
				end2 = p2.getName().substring(p2.getName().lastIndexOf(":"));
			else
				end2 = p2.getName();
			return end1.compareTo(end2);
		}
	}
}

modules/security/security-management/src/main/java/org/openiot/security/mgmt/UsersController.java
/**
 * Copyright (c) 2011-2014, OpenIoT
 *
 * This library is free software; you can redistribute it and/or
 * modify it either under the terms of the GNU Lesser General Public
 * License version 2.1 as published by the Free Software Foundation
 * (the "LGPL"). If you do not alter this
 * notice, a recipient may use your version of this file under the LGPL.
 *
 * You should have received a copy of the LGPL along with this library
 * in the file COPYING-LGPL-2.1; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY
 * OF ANY KIND, either express or implied. See the LGPL  for
 * the specific language governing rights and limitations.
 *
 * Contact: OpenIoT mailto: info@openiot.eu
 */

package org.openiot.security.mgmt;

import static org.openiot.security.mgmt.Utils.EmptyPermissionList;
import static org.openiot.security.mgmt.Utils.EmptyRoleList;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import org.jasig.cas.services.RegisteredService;
import org.openiot.lsm.security.oauth.mgmt.Permission;
import org.openiot.lsm.security.oauth.mgmt.Role;
import org.openiot.lsm.security.oauth.mgmt.User;

/**
 * @author Mehdi Riahi
 *
 */
@ManagedBean
@ViewScoped
public class UsersController extends AbstractController {
	// Are you sure you want to delete Role '#{role.name}'?&lt;br&gt;It will be revoke from the
	// users having this role.
	private static final long serialVersionUID = 5365682876974798395L;

	private Role selectedRole;

	private User selectedUser;

	private Role selectedOtherRole;

	private Map<Role, List<User>> roleUsers;

	private List<User> allUsers;

	private List<Role> allRoles;

	private Map<Long, RegisteredService> allServices;

	@ManagedProperty(value = "#{securityManagerService}")
	private SecurityManagerService securityManagerService;

	private long selectedServiceId = -1;

	private String selectedServiceIdStr = null;

	public UsersController() {
	}

	public List<User> getUsers() {
		if (allUsers == null) {
			allRoles = securityManagerService.getAllRoles();
			roleUsers = new HashMap<Role, List<User>>();
			for (Role role : allRoles)
				roleUsers.put(role, securityManagerService.getRoleUsers(role));

			allUsers = securityManagerService.getAllUsers();

			final List<RegisteredService> services = securityManagerService.getAllServices();
			allServices = new HashMap<Long, RegisteredService>(services.size());
			for (RegisteredService registeredService : services) {
				String name = registeredService.getName();
				if (Utils.acUtil.hasPermission("admin:user_mgmt:" + name))
					allServices.put(registeredService.getId(), registeredService);
			}
		}
		return allUsers;
	}

	public void setSecurityManagerService(SecurityManagerService securityManagerService) {
		this.securityManagerService = securityManagerService;
	}

	public void removeRole(Role role) {
		// TODO: extremely dangerous! replace with revokeRoleFromUser(user, role)
		if (selectedUser != null) {
			selectedUser.getRoles().remove(selectedRole);

			securityManagerService.deleteUser(selectedUser.getUsername());
			securityManagerService.addUser(selectedUser);
			addInfoMessage("Role revoked from the selected user", role.getName());
		}
		if (role.equals(selectedRole)) {
			setSelectedRole(null);
		}
	}

	public void removeUser(User user) {
		if (user.equals(selectedUser)) {
			allUsers.remove(user);
			securityManagerService.deleteUser(selectedUser.getUsername());
			addInfoMessage("User Deleted", user.getUsername());
			setSelectedUser(null);
		}
	}

	public List<Role> getSelectedUserRoles() {
		List<Role> userRoles = EmptyRoleList;
		if (selectedUser != null && selectedServiceId > -1) {
			userRoles = new ArrayList<Role>();
			if (selectedUser.getRoles() == null)
				selectedUser.setRoles(userRoles);
			else {
				for (Role role : selectedUser.getRoles())
					if (role.getServiceId().equals(selectedServiceId))
						userRoles.add(role);
			}
		}
		return userRoles;
	}

	public List<Role> getSelectedUserOtherRoles() {
		if (selectedUser != null) {
			List<Role> currentRoles = selectedUser.getRoles();
			List<Role> roles = new ArrayList<Role>();

			for (Role role : allRoles)
				if (role.getServiceId().equals(selectedServiceId) && (currentRoles == null || !currentRoles.contains(role)))
					roles.add(role);
			return roles;
		}
		return EmptyRoleList;
	}

	public List<Permission> getSelectedRolePermissions() {
		List<Permission> list = EmptyPermissionList;
		if (selectedRole != null) {
			if (selectedRole.getPermissions() == null) {
				list = new ArrayList<Permission>();
				selectedRole.setPermissions(list);
			} else {
				list = selectedRole.getPermissions();
			}
		}
		return list;
	}

	public Role getSelectedRole() {
		return selectedRole;
	}

	public void setSelectedRole(Role selectedRole) {
		this.selectedRole = selectedRole;
	}

	public User getSelectedUser() {
		return selectedUser;
	}

	public void setSelectedUser(User selectedUser) {
		this.selectedUser = selectedUser;
		// setSelectedServiceIdStr(null);
		setSelectedRole(null);
		setSelectedOtherRole(null);
	}

	public Role getSelectedOtherRole() {
		return selectedOtherRole;
	}

	public void setSelectedOtherRole(Role selectedOtherRole) {
		this.selectedOtherRole = selectedOtherRole;
	}

	public List<RegisteredService> getAllServices() {
		return new ArrayList<RegisteredService>(allServices.values());
	}

	public Long getSelectedServiceId() {
		return selectedServiceId;
	}

	public void setSelectedServiceId(Long selectedServiceId) {
		this.selectedServiceId = selectedServiceId;
	}

	public String getSelectedServiceIdStr() {
		return selectedServiceIdStr;
	}

	public void setSelectedServiceIdStr(String selectedServiceIdStr) {
		this.selectedServiceIdStr = selectedServiceIdStr;
		try {
			setSelectedServiceId(Long.parseLong(selectedServiceIdStr));
		} catch (NumberFormatException e) {
			setSelectedServiceId(-1L);
		}
		setSelectedRole(null);
		setSelectedOtherRole(null);
	}

	public String getSelectedServiceName() {
		if(allServices != null && selectedServiceId > -1 && allServices.containsKey(selectedServiceId))
			return allServices.get(selectedServiceId).getName();
		return "SELECTED_SERVICE_NOT_FOUND";
	}

	public void addRole() {
		// TODO: extremely dangerous! replace with grantRoleToUser(user, role)
		if (selectedOtherRole != null && selectedUser != null) {
			selectedUser.getRoles().add(selectedOtherRole);
			securityManagerService.deleteUser(selectedUser.getUsername());
			securityManagerService.addUser(selectedUser);
			addInfoMessage("Role added to the selected user <" + selectedUser.getUsername() + ">", selectedOtherRole.getName());
			setSelectedOtherRole(null);
		} else {
			addWarnMessage("There is no new role to add", "");
		}
	}

}

modules/security/security-management/src/main/webapp/error.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
        xmlns:ui="http://java.sun.com/jsf/facelets"
        xmlns:f="http://java.sun.com/jsf/core"
        xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui" template="/WEB-INF/templates/main.xhtml">

        <ui:define name="content">

                <h2>Oops! something went wrong!</h2>

        </ui:define>
</ui:composition>

modules/security/security-management/src/main/webapp/index.jsp
<jsp:forward page="home.jsf"></jsp:forward>

modules/security/security-management/src/main/webapp/perms.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html" xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core" xmlns:openiot="http://openiot.org/tags" xmlns:c="http://java.sun.com/jsp/jstl/core">

<head />
<body>
	<ui:composition template="/WEB-INF/templates/main.xhtml">
		<ui:define name="title">Manage Permissions</ui:define>
		<ui:define name="nav-links">
			<li><a href="home.jsf">Home</a></li>
			<openiot:hasPermission name="admin:user_mgmt_general">
				<li><a href="roles.jsf">Manage roles</a></li>
				<li><a href="users.jsf">Manage users</a></li>
				<li class="active"><a href="perms.jsf">Manage permissions</a></li>
				<openiot:hasPermission name="admin:add_services">
					<li><a href="services.jsf">Manage services</a></li>
				</openiot:hasPermission>
			</openiot:hasPermission>
			<c:if test="${permissionsController.isDemoEnabled()}">
				<li><a href="guest_services.jsf">Guest services</a></li>
			</c:if>
		</ui:define>
		<ui:define name="content">
			<openiot:hasPermission name="admin:user_mgmt_general">
				<p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />
				<p:layout fullPage="false" id="layout" style="min-height:800px;">

					<p:layoutUnit position="north">
						<h:form id="serviceForm">
							<p:selectOneMenu value="#{permissionsController.selectedServiceIdStr}" id="serviceSelector">
								<f:selectItem itemLabel="Select Service" itemValue="#{null}" />
								<f:selectItems value="#{permissionsController.allServicesAsList}" var="service" itemValue="#{service.id}" itemLabel="#{service.name}" />
								<p:ajax update=":rolesForm:permissionsPanel :rolesForm:usersTable :permForm:permRolesPanel" immediate="true" />
							</p:selectOneMenu>
						</h:form>
					</p:layoutUnit>

					<p:layoutUnit position="west" minSize="200" size="500" resizable="true">
						<h:form id="rolesForm">
							<!-- Form must be inside layoutUnit otherwise strange behavior -->
							<!-- TODO: allow selecting multiple rows for deletion -->
							<!-- TODO: Sort names based on the service name ending -->
							<h:panelGrid columns="1" style="width:100%" cellpadding="5">
								<h:panelGroup id="permissionsPanel" layout="block" style="width:100%">
									<p:dataTable var="perm" value="#{permissionsController.permissions}" id="permissionsTable" tableStyle="width:100%;" selectionMode="single"
										selection="#{permissionsController.selectedPermission}" rowKey="#{perm.name}" emptyMessage="Permission list is empty." resizableColumns="true" 
										paginator="true" rows="10" paginatorPosition="bottom">

										<p:ajax event="rowSelect" update=":rolesForm:permissionsTable:removePermBtn :rolesForm:usersTable :permForm:permRolesPanel" />
										<p:ajax event="rowUnselect" update=":rolesForm:permissionsTable:removePermBtn :rolesForm:usersTable :permForm:permRolesPanel" />

										<f:facet name="header">
											<h:outputText value="Available Permissions" />
										</f:facet>

										<p:column headerText="Name" width="50%">
											<h:outputText value="#{perm.name}" />
										</p:column>

										<p:column headerText="Description" width="50%">
											<h:outputText value="#{perm.description}" />
										</p:column>

										<f:facet name="footer">
											<openiot:hasPermission name="admin:create_permission:#{permissionsController.selectedServiceName}">
												<p:commandButton id="addPermBtn" update=":dlgForm:addPermissionDlg" icon="ui-icon-plusthick" title="Add Permission"
													onclick="PF('addPermissionDlgVar').show(); return false;" disabled="#{empty permissionsController.selectedServiceIdStr}" />
											</openiot:hasPermission>
												<p:commandButton id="removePermBtn" icon="ui-icon-closethick" title="Delete"
													actionListener="#{permissionsController.removePermission(permissionsController.selectedPermission)}"
													update=":rolesForm:permissionsPanel :rolesForm:usersTable :permForm:permRolesPanel" immediate="true"
													disabled="#{not permissionsController.hasPermissionDeletionPermission() or empty permissionsController.selectedPermission}">
													<p:confirm header="Confirmation" message="Are you sure you want to delete Permission?" icon="ui-icon-alert" />
												</p:commandButton>

										</f:facet>
									</p:dataTable>
								</h:panelGroup>

								<h:panelGroup layout="block" style="width:100%">
									<p:dataTable var="user" value="#{permissionsController.selectedPermissionUsers}" id="usersTable" resizableColumns="true"
										style="table-layout: fixed; font-size:smaller;" emptyMessage="User list is empty.">

										<f:facet name="header">
											<h:outputText value="#{permissionsController.selectedPermission == null ? 'Permission Users' : 'Permission Users ('.concat(permissionsController.selectedPermission.name).concat(')')}" />
										</f:facet>

										<p:column headerText="Full name" width="35%">
											<h:outputText value="#{user.name}" />
										</p:column>

										<p:column headerText="Username" width="30%">
											<h:outputText value="#{user.username}" />
										</p:column>

										<p:column headerText="Email" width="35%">
											<h:outputText value="#{user.email}" />
										</p:column>


										<f:facet name="footer">
										</f:facet>

									</p:dataTable>
								</h:panelGroup>

							</h:panelGrid>
						</h:form>
					</p:layoutUnit>

					<p:layoutUnit position="center">
						<h:form id="permForm">
							<h:panelGroup layout="block" style="width:100%">
								<p:panelGrid id="permRolesPanel" columns="1" style="width:100%">
									<f:facet name="header">Permission Roles</f:facet>
									<p:dataTable var="role" value="#{permissionsController.selectedPermissionRoles}" rowKey="#{role.name}" tableStyle="width:100%"
										emptyMessage="Role list is empty.">
										<p:column headerText="Role Name" width="45%">
											<h:outputText value="#{role.name}" />
										</p:column>

										<p:column headerText="Role Description" width="45%">
											<h:outputText value="#{role.description}" />
										</p:column>

									</p:dataTable>
								</p:panelGrid>
							</h:panelGroup>
						</h:form>
					</p:layoutUnit>

					<p:confirmDialog global="true" showEffect="fade" hideEffect="explode">
						<p:commandButton value="Yes" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
						<p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
					</p:confirmDialog>

					<h:form id="dlgForm">
						<p:dialog id="addPermissionDlg" header="Add Permission" widgetVar="addPermissionDlgVar" modal="true" width="400" dynamic="true">
							<p:ajax event="close" update=":dlgForm:addPermissionDlg" />
							<h:panelGrid columns="2" style="margin-bottom:10px; width:100%;" cellpadding="5" columnClasses="labelColumn">
								<!-- <p:messages for="addPermissionDlg" id="addPermissionDlg_messages" showDetail="true" autoUpdate="true" closable="true" />  -->
								<h:outputLabel for="name" value="Name:" />
								<p:inputText id="name" value="#{permissionsController.newPermission.name}" required="true" requiredMessage="Permission name must not be empty." style="width:90%;"/>
								<h:outputLabel for="description" value="Description:" />
								<p:inputText id="description" value="#{permissionsController.newPermission.description}" required="true"
									requiredMessage="Permission description must not be empty." style="width:90%;"/>
								<f:facet name="footer">
									<p:commandButton id="addPermissionDlg_addButton" value="Add" actionListener="#{permissionsController.addPermission}"
										oncomplete="handleAddPermissionRequest(xhr, status, args)" update=":rolesForm:permissionsPanel" />
									<p:commandButton immediate="true" id="addPermissionDlg_cancelButton" value="Cancel" actionListener="#{permissionsController.cancelAddPermission}"
										oncomplete="PF('addPermissionDlgVar').hide()" />
								</f:facet>
							</h:panelGrid>
						</p:dialog>

					</h:form>

				</p:layout>
				<script type="text/javascript">  
    function handleAddPermissionRequest(xhr, status, args) {  
        if(args.validationFailed || !args.permissionAdded) {  
            PF('addPermissionDlgVar').jq.effect("shake", { times:5 }, 100);  
        }   
        else {  
            PF('addPermissionDlgVar').hide();  
        }  
    }  
</script>
			</openiot:hasPermission>
		</ui:define>
	</ui:composition>
</body>
</html>