ui/ui.requestPresentation/src/main/java/org/openiot/ui/request/presentation/web/scopes/controllers/pages/LoginPageController.java
/**
 *    Copyright (c) 2011-2014, OpenIoT
 *   
 *    This file is part of OpenIoT.
 *
 *    OpenIoT is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU Lesser General Public License as published by
 *    the Free Software Foundation, version 3 of the License.
 *
 *    OpenIoT is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU Lesser General Public License for more details.
 *
 *    You should have received a copy of the GNU Lesser General Public License
 *    along with OpenIoT.  If not, see <http://www.gnu.org/licenses/>.
 *
 *     Contact: OpenIoT mailto: info@openiot.eu
 */

package org.openiot.ui.request.presentation.web.scopes.controllers.pages;

import java.io.IOException;
import java.io.Serializable;
import java.util.ResourceBundle;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.openiot.security.client.AccessControlUtil;
import org.openiot.ui.request.commons.providers.SchedulerAPIWrapper;
import org.openiot.ui.request.commons.providers.exceptions.APICommunicationException;
import org.openiot.ui.request.commons.providers.exceptions.APIException;
import org.openiot.ui.request.presentation.web.scopes.application.ApplicationBean;
import org.openiot.ui.request.presentation.web.scopes.session.SessionBean;
import org.openiot.ui.request.presentation.web.scopes.session.context.pages.LoginPageContext;
import org.openiot.ui.request.presentation.web.util.FaceletLocalization;

/**
 * 
 * @author Achilleas Anagnostopoulos (aanag) email: aanag@sensap.eu
 */
@ManagedBean(name = "loginPageController")
@RequestScoped
public class LoginPageController implements Serializable {
	private static final long serialVersionUID = 1L;

	// Cached context
	private LoginPageContext cachedContext;
	// Injected properties
	@ManagedProperty(value = "#{applicationBean}")
	protected transient ApplicationBean applicationBean;
	@ManagedProperty(value = "#{sessionBean}")
	protected transient SessionBean sessionBean;
	protected transient ResourceBundle messages;

	public LoginPageController() {
		this.messages = FaceletLocalization.getLocalizedResourceBundle();
	}

	public LoginPageContext getContext() {
		if (cachedContext == null) {
			cachedContext = (LoginPageContext) (sessionBean == null ? ApplicationBean.lookupSessionBean() : sessionBean).getContext("loginPageContext");
			if (cachedContext == null) {
				cachedContext = new LoginPageContext();
			}
		}
		return cachedContext;
	}

	// ------------------------------------
	// Controllers
	// ------------------------------------
	public void handleLogout() throws IOException {
		sessionBean.setUserId(null);
		getContext().dispose();

//		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		FacesContext.getCurrentInstance().getExternalContext().redirect("../logout?faces-redirect=true");

	}

	public void handleLogin() {
		LoginPageContext context = getContext();
		
		// Invoke user login service API
		try{
			String userId = SchedulerAPIWrapper.userLogin(context.getEmail(), context.getPassword());
			sessionBean.setUserId(userId);
			context.dispose();

			applicationBean.redirect("/pages/requestPresentation.xhtml?faces-redirect=true");
			return;
		}catch(APICommunicationException ex){
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, messages.getString("GROWL_ERROR_HEADER"), FaceletLocalization.getLocalisedMessage(messages, "ERROR_CONNECTING_TO_REGISTRATION_SERVICE")));
		}catch(APIException ex){
			context.dispose();
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_FATAL, messages.getString("GROWL_ERROR_HEADER"), FaceletLocalization.getLocalisedMessage(messages, "ERROR_INVALID_CREDENTIALS")));
		}
	}

	// ------------------------------------
	// Helpers
	// ------------------------------------
	public void setApplicationBean(ApplicationBean applicationBean) {
		this.applicationBean = applicationBean;
	}

	public void setSessionBean(SessionBean sessionBean) {
		this.sessionBean = sessionBean;
	}
	
	
	public String getUsername() {
		String userIdURI = sessionBean.getUserId();
		if (userIdURI != null) {
			return userIdURI.substring(userIdURI.lastIndexOf("/") + 1);
		}
		return null;
	}

}

ui/ui.requestPresentation/src/main/webapp/pages/error.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:s="http://www.sensap.eu/jsf"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:dialogs="http://java.sun.com/jsf/composite/components/dialogs"
	xmlns:widgets="http://java.sun.com/jsf/composite/components/widgets">

<f:view contentType="text/html">
	<h:body>
          <h2>Oops! something went wrong!</h2>
	</h:body>
</f:view>
</html>

ui/ui.requestPresentation/src/main/webapp/pages/login.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:s="http://www.sensap.eu/jsf"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:dialogs="http://java.sun.com/jsf/composite/components/dialogs"
	xmlns:widgets="http://java.sun.com/jsf/composite/components/widgets"
	xmlns:shiro="http://shiro.apache.org/tags">

<f:view contentType="text/html">
	<h:head>
		<meta content='text/html; charset=UTF-8' http-equiv="Conmenutent-Type" />
		<h:outputStylesheet library="css" name="core.css" />
		<h:outputScript library="js" name="core.js" />
		<title>#{messages.UI_REQUEST_PRESENTATION_TITLE}</title>
	</h:head>

	<h:body styleClass="login" id="body">
		<h:form id="util">
			<p:growl widgetVar="growl" escape="false" autoUpdate="true"
				showSummary="false" showDetail="true" sticky="false" life="3000" />
		</h:form>

		<pe:blockUI widgetVar="windowBlockUI"
			targetSelector=".login">
			<span class="ui-icon-loader-big"></span>
		</pe:blockUI>

		<div align="center">
			<div class="logo" />
			<div class="slogan">Open Source Solution for the Internet of
				Things into the Cloud</div>
		</div>

		<p:separator />

		
		<p:outputPanel layout="block" style="text-align:center;">
			<h:button value="#{messages.UI_LOGIN_REQUEST_PRESENTATION}" outcome="requestPresentation.xhtml" />
			<ui:remove>
			<shiro:guest>
				<h:button value="Log out of CAS" onclick="window.open('#{loginPageController.signOutOfCASLink}', '_blank');"/>
			</shiro:guest>
			</ui:remove>
		</p:outputPanel>

		<ui:remove>
		<p:outputPanel layout="block" style="text-align:center;">
			<h:panelGrid columns="2"
				style="margin:0 auto;"
				cellpadding="20"
				columnClasses="align-top, align-top">
				<p:panel header="#{messages.UI_LOGIN_LOGIN_BUTTON}" style="width:250px;">
					<h:form>
						<h:panelGrid columns="2">
							<p:outputLabel value="#{messages.UI_LOGIN_EMAIL}" />
							<p:inputText value="#{loginPageController.context.email}" />

							<p:outputLabel value="#{messages.UI_LOGIN_PASSWORD}" />
							<p:inputText type="password"
								value="#{loginPageController.context.password}" />
						</h:panelGrid>
						<hr />
						<p:outputPanel layout="block" style="text-align:right;">
							<p:commandButton process="@form" update="@form"
								actionListener="#{loginPageController.handleLogin()}"
								value="#{messages.UI_LOGIN_LOGIN_BUTTON}" 
								onclick="windowBlockUI.block();"
								oncomplete="windowBlockUI.unblock();"/>
						</p:outputPanel>
					</h:form>
				</p:panel>

			</h:panelGrid>
		</p:outputPanel>
		</ui:remove>

		<p:dialog></p:dialog>
	</h:body>

</f:view>
</html>

ui/ui.requestPresentation/src/main/webapp/pages/requestPresentation.xhtml
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:s="http://www.sensap.eu/jsf"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:dialogs="http://java.sun.com/jsf/composite/components/sensap/dialogs"
	xmlns:shiro="http://shiro.apache.org/tags">

<f:view contentType="text/html">
	<f:event type="javax.faces.event.PreRenderViewEvent"
		listener="#{requestPresentationPageController.doAccessControl}" />

	<h:head>
		<meta content='text/html; charset=UTF-8' http-equiv="Content-Type" />
		<h:outputStylesheet library="css" name="core.css" />
		<h:outputScript library="js" name="core.js" />
		<h:outputScript library="js" name="jqplot/jquery.jqplot.min.js" />
		<h:outputScript library="js" name="jqplot/jqplot.canvasTextRenderer.min.js" />
		<h:outputScript library="js" name="jqplot/jqplot.canvasAxisTickRenderer.min.js" />
		<h:outputScript library="js" name="jqplot/jqplot.categoryAxisRenderer.min.js" />
		<script src="http://maps.google.com/maps/api/js?sensor=false"
			type="text/javascript"></script>
		<title>#{messages.UI_REQUEST_PRESENTATION_TITLE}</title>
	</h:head>

	<h:body styleClass="request-presentation" id="body">
		<h:form id="util">
			<p:growl widgetVar="growl" escape="false" autoUpdate="true"
				showSummary="false" showDetail="true" sticky="true"
				severity="error,fatal" />
			<p:growl widgetVar="growl2" escape="false" autoUpdate="true"
				showSummary="false" showDetail="true" severity="info, warn"
				life="3000" />
			<p:poll process="@this" update="@this" interval="600"
				listener="#{requestPresentationPageController.keepAlivePing}" />

		</h:form>

		<pe:blockUI widgetVar="windowBlockUI"
			targetSelector=".request-presentation">
			<span class="ui-icon-loader-big"></span>
		</pe:blockUI>


		<pe:layout id="pageLayout" stateCookie="true" fullPage="true">

			<!-- Menubar -->
			<pe:layoutPane position="north" size="42" closable="false"
				resizable="false"
				styleClassContent="no-border menubar-layout-container">
				<h:form id="menubar">
					<p:menubar autoDisplay="false">
						<p:submenu label="#{messages.UI_MENUBAR_FILE}"
							icon="ui-icon-document">

							<p:submenu label="#{messages.UI_MENUBAR_FILE_OPEN}"
								rendered="#{! requestPresentationPageController.context.appManager.availableOAMOs.isEmpty()}"
								icon="ui-icon-folder-open">

								<c:forEach
									items="#{requestPresentationPageController.context.appManager.availableOAMOs}"
									var="entry">
									<p:menuitem value="#{entry.name}"
										actionListener="#{requestPresentationPageController.loadApplication(entry.name)}"
										process="@this" onclick="windowBlockUI.block();"
										oncomplete="windowBlockUI.unblock();"
										update=":dashboardForm, :menubar" />
								</c:forEach>

							</p:submenu>

							<p:separator />

							<p:menuitem value="#{messages.UI_MENUBAR_FILE_REFRESH}"
								icon="ui-icon-refresh"
								actionListener="#{requestPresentationPageController.reloadApplications()}"
								process="@this" onclick="windowBlockUI.block();"
								oncomplete="windowBlockUI.unblock();"
								update=":dashboardForm, :menubar" />

						</p:submenu>

						<p:submenu label="#{messages.UI_MENUBAR_APP}" icon="ui-icon-gear">

							<p:menuitem value="#{messages.UI_MENUBAR_APP_REFRESH}"
								disabled="#{empty requestPresentationPageController.context.appManager.selectedOAMO}"
								icon="ui-icon-refresh"
								onclick="refreshAllWidgets();return false;" />
						</p:submenu>

						<f:facet name="options">
							<p:outputLabel value="#{messages.UI_MENUBAR_ACTIVE_APP}" />
							<p:button icon="ui-icon-document" style="margin-left:10px;"
								value="#{empty requestPresentationPageController.context.appManager.selectedOAMO ? '-' : requestPresentationPageController.context.appManager.selectedOAMO.name}"
								onclick="return false;" />


							<shiro:user>
								<p:commandButton icon="ui-icon-unlocked"
									style="margin-left:10px;"
									value="#{messages.UI_LOGIN_LOGOUT_BUTTON} (#{loginPageController.username})" process="@this"
									actionListener="#{loginPageController.handleLogout()}" />
							</shiro:user>	
						</f:facet>

					</p:menubar>
				</h:form>
			</pe:layoutPane>

			<pe:layoutPane position="center" styleClass="no-border">
				<h:form id="dashboardForm"
					rendered="#{! empty requestPresentationPageController.context}">
					<p:dashboard
						binding="#{requestPresentationPageController.dashboard}" />

					<p:outputLabel
						rendered="#{empty requestPresentationPageController.context.appManager.selectedOAMO}"
						value="#{messages.UI_WIDGET_NO_APPLICATION_SELECTED}"
						styleClass="no-application-selected" />
				</h:form>

			</pe:layoutPane>

		</pe:layout>
		<div style="display: none;">
			<p:gmap center="41.381542, 2.122893" zoom="15" type="HYBRID"
				style="width:1px;height:1px" />
		</div>
	</h:body>

	<h:form>
		<p:remoteCommand
			rendered="#{empty requestPresentationPageController.context.appManager}"
			name="loadApplications" autoRun="true"
			actionListener="#{requestPresentationPageController.reloadApplications()}"
			process="@this" update=":dashboardForm, :menubar"
			onstart="windowBlockUI.block();"
			oncomplete="windowBlockUI.unblock();" />

		<p:remoteCommand name="updateWidget"
			actionListener="#{requestPresentationPageController.updateWidget()}"
			async="true"
			process="@this" />

		<script type="text/javascript"></script>
			// Setup a timer to periodically update the dashboards.
			// See core.js for the actual refresh code
			$(document).ready(function(){
				setTimeout(refreshAllWidgets, 60000);	
			});
	</h:form>


</f:view>
</html>